development:
  dialect: postgres
  database: otpify_development
  user: postgres
  password: mysecretpassword
  host: 127.0.0.1
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:mysecretpassword@127.0.0.1:5432/otpify_test?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:mysecretpassword@127.0.0.1:5432/otpify_production?sslmode=disable"}}